deps: Add tables12.0.0.go
Fixes the following error from commit 6dc484c1779a7c2bdfa1e4b83f8a323a780f193e

../vendor/golang.org/x/text/unicode/bidi/prop.go:15:12: undefined: newBidiTrie
../vendor/golang.org/x/text/unicode/bidi/prop.go:45:9: undefined: xorMasks
../vendor/golang.org/x/text/unicode/bidi/prop.go:89:28: undefined: bidiValues
../vendor/golang.org/x/text/unicode/bidi/prop.go:96:8: undefined: bidiIndex
../vendor/golang.org/x/text/unicode/bidi/prop.go:106:8: undefined: bidiIndex
../vendor/golang.org/x/text/unicode/bidi/prop.go:112:7: undefined: bidiIndex
../vendor/golang.org/x/text/unicode/bidi/prop.go:122:8: undefined: bidiIndex
../vendor/golang.org/x/text/unicode/bidi/prop.go:128:7: undefined: bidiIndex
../vendor/golang.org/x/text/unicode/bidi/prop.go:134:7: undefined: bidiIndex
../vendor/golang.org/x/text/unicode/bidi/prop.go:152:28: undefined: bidiValues
../vendor/golang.org/x/text/unicode/bidi/prop.go:152:28: too many errors
../vendor/golang.org/x/text/unicode/norm/composition.go:466:2: undefined: recompMapOnce
../vendor/golang.org/x/text/unicode/norm/forminfo.go:134:20: undefined: firstMulti
../vendor/golang.org/x/text/unicode/norm/forminfo.go:134:44: undefined: endMulti
../vendor/golang.org/x/text/unicode/norm/forminfo.go:153:7: undefined: decomps
../vendor/golang.org/x/text/unicode/norm/trie.go:18:10: undefined: nfcSparseValues
../vendor/golang.org/x/text/unicode/norm/trie.go:19:10: undefined: nfcSparseOffset
../vendor/golang.org/x/text/unicode/norm/trie.go:23:10: undefined: nfkcSparseValues
../vendor/golang.org/x/text/unicode/norm/trie.go:24:10: undefined: nfkcSparseOffset
../vendor/golang.org/x/text/unicode/norm/trie.go:28:13: undefined: newNfcTrie
../vendor/golang.org/x/text/unicode/norm/trie.go:29:13: undefined: newNfkcTrie
../vendor/golang.org/x/text/unicode/norm/forminfo.go:153:7: too many errors
FAIL	github.com/DNSCrypt/dnscrypt-proxy/dnscrypt-proxy [build failed]